# Generated by Django 4.0.4 on 2022-05-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Province',
            new_name='province',
        ),
    ]
