# Generated by Django 4.0.4 on 2022-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='website',
            new_name='Your_Job',
        ),
    ]
