# Generated by Django 4.0.4 on 2022-05-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='herosection/')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('garge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Appoinment',
        ),
        migrations.AddField(
            model_name='herosectionproperty',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propertystatus'),
        ),
    ]
