# Generated by Django 4.0.4 on 2022-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_herosectionproperty_propertystatus_delete_appoinment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectionproperty',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
