# Generated by Django 4.0.4 on 2022-05-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_rename_province_city_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=None)),
                ('bedrooms', models.IntegerField(default=0)),
                ('livingrooms', models.IntegerField(default=0)),
                ('washrooms', models.IntegerField(default=0)),
                ('basement', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='properties/')),
                ('ref_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.properties')),
            ],
        ),
    ]
