# Generated by Django 4.0.4 on 2022-05-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_province_city_province'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
    ]
