# Generated by Django 4.0.4 on 2022-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_properties_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
