# Generated by Django 4.0.4 on 2022-05-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_image_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='Name Here', max_length=50),
        ),
    ]
