# Generated by Django 4.0.4 on 2022-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyarea',
            field=models.IntegerField(default=0),
        ),
    ]
