# Generated by Django 4.0.4 on 2022-05-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.propertystatus'),
        ),
    ]
