# Generated by Django 4.0.4 on 2022-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
    ]
