# Generated by Django 4.0.4 on 2022-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_image_property_image1_property_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='full_house_image',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
    ]
