# Generated by Django 4.0.4 on 2022-05-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_carouseldisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='header_display',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.carouseldisplay'),
        ),
    ]
