# Generated by Django 4.0.4 on 2022-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Year_Build',
            field=models.IntegerField(default=2000),
        ),
    ]
