# Generated by Django 4.0.4 on 2022-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_property_year_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.FileField(blank=True, upload_to='properties/'),
        ),
    ]
